---
- name: Comware BGP Group testing
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Configure BGP and create group
      comware_bgp_group:
        bgp_as: 200
        group: evpn
        group_type: internal
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

    - name: Configure peer connection interface
      comware_bgp_group:
        bgp_as: 200
        peer: evpn
        peer_connect_intf: LoopBack0
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

    - name: Join peer 1.1.1.1 to the group
      comware_bgp_group:
        bgp_as: 200
        peer: 1.1.1.1
        peer_in_group: evpn
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

    - name: Join peer 3.3.3.3 to the group
      comware_bgp_group:
        bgp_as: 200
        peer: 3.3.3.3
        peer_in_group: evpn
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

    - name: Create address-family view and configure it
      comware_bgp_group:
        bgp_as: 200
        address_family: l2vpn
        evpn: true
        policy_vpn_target: disable
        peer: evpn
        reflect_client: true
        peer_group_state: true
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"

    - name: Remove BGP configuration
      comware_bgp_group:
        bgp_as: 200
        state: default
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
