---
- name: Comware NTP Configuration
  hosts: all
  gather_facts: no
  connection: local

  vars:
    ntp_key:
      id: 42
      authmode: md5
      authkey: anicekey
    ntp_server: "10.1.1.1"
    interface: "GigabitEthernet1/0/7"

  tasks:
    - name: Configure NTP authentication
      comware_ntp:
        service: ntp
        keyid: "{{ ntp_key.id }}"
        authmode: "{{ ntp_key.authmode }}"
        authkey: "{{ ntp_key.authkey }}"
        reliable: true
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ntp_auth

    - name: Configure NTP stratum level
      comware_ntp:
        stratum: 2
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ntp_stratum

    - name: Configure NTP client
      comware_ntp:
        service: ntp
        keyid: "{{ ntp_key.id }}"
        hostmode: client
        ipadd: "{{ ntp_server }}"
        name: "{{ interface }}"
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ntp_client

    - name: Remove trusted key
      comware_ntp:
        state: absent
        del_rel_alone: true
        service: ntp
        keyid: "{{ ntp_key.id }}"
        reliable: false
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ntp_key_removal

    - name: Remove all authentication keys
      comware_ntp:
        state: absent
        service: ntp
        keyid: "{{ ntp_key.id }}"
        del_auth_all: true
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ntp_auth_removal

    - name: Display NTP configuration results
      debug:
        msg: |
          NTP Authentication: {{ ntp_auth.msg | default('N/A') }}
          NTP Stratum: {{ ntp_stratum.msg | default('N/A') }}
          NTP Client: {{ ntp_client.msg | default('N/A') }}
          Key Removal: {{ ntp_key_removal.msg | default('N/A') }}
          Auth Removal: {{ ntp_auth_removal.msg | default('N/A') }}
