---
- name: Network Reachability Tests
  hosts: all
  gather_facts: no
  connection: local

  vars:
    test_hosts:
      - host: 8.8.8.8
        description: "Google DNS"
      - host: 300.8.8.8
        description: "Invalid IP (for failure testing)"

  tasks:
    - name: Test network reachability
      comware_ping:
        host: "{{ item.host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: ping_results
      ignore_errors: "{{ item.host == '300.8.8.8' }}"
      loop: "{{ test_hosts }}"
      loop_control:
        label: "Testing reachability to {{ item.host }} ({{ item.description }})"

    - name: Display ping results
      debug:
        msg: |
          Host: {{ item.item.host }}
          Status: {% if item.failed %}Failed{% else %}Success{% endif %}
          Loss Rate: {{ item.response.loss_rate }}
          Avg Response: {{ item.response.avg }}ms
          Packets Sent: {{ item.response.packets_tx }}
          Packets Received: {{ item.response.packets_rx }}
      when: item.item.host != '300.8.8.8'
      loop: "{{ ping_results.results | default([ping_results]) }}"
      loop_control:
        label: "{{ item.item.host }}"

    - name: Verify failure for invalid IP
      assert:
        that:
          - item.failed == true
        fail_msg: "Expected ping to {{ item.item.host }} to fail but it succeeded"
        success_msg: "Ping to {{ item.item.host }} failed as expected"
      when: item.item.host == '300.8.8.8'
      loop: "{{ ping_results.results | default([ping_results]) }}"
      loop_control:
        label: "{{ item.item.host }}"
