---
- name: Configure Port Channel (LAG)
  hosts: all
  gather_facts: no
  connection: local

  vars:
    portchannel:
      group: 100
      type: routed
      mode: static
      min_ports: 2
      max_ports: 4
    interfaces:
      - FortyGigE1/0/27
      - FortyGigE1/0/28
      - FortyGigE1/0/29
      - FortyGigE1/0/30

  tasks:
    - name: Ensure port channel {{ portchannel.group }} does not exist initially
      comware_portchannel:
        group: "{{ portchannel.group }}"
        type: "{{ portchannel.type }}"
        state: absent
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: portchannel_removal

    - name: Verify port channel removal
      assert:
        that:
          - portchannel_removal.end_state == {}
        fail_msg: "Failed to remove port channel {{ portchannel.group }}"
        success_msg: "Port channel {{ portchannel.group }} removed successfully"

    - name: Configure interfaces for port channel
      comware_interface:
        name: "{{ item }}"
        type: "{{ portchannel.type }}"
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      loop: "{{ interfaces }}"
      register: interface_config

    - name: Configure port channel with members (Static Mode)
      comware_portchannel:
        group: "{{ portchannel.group }}"
        members: "{{ interfaces }}"
        type: "{{ portchannel.type }}"
        mode: "{{ portchannel.mode }}"
        min_ports: "{{ portchannel.min_ports }}"
        max_ports: "{{ portchannel.max_ports }}"
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: portchannel_static

    - name: Verify static port channel configuration
      debug:
        var: portchannel_static.end_state

    - name: Configure port channel with LACP (Dynamic Mode)
      comware_portchannel:
        group: "{{ portchannel.group }}"
        members: "{{ interfaces[0:2] }}"  # Use first two interfaces for LACP
        type: "{{ portchannel.type }}"
        mode: dynamic
        lacp_mode: active
        lacp_edge: enabled
        min_ports: 2
        max_ports: 4
        username: "{{ username }}"
        password: "{{ password }}"
        hostname: "{{ inventory_hostname }}"
      register: portchannel_lacp

    - name: Verify LACP port channel configuration
      debug:
        var: portchannel_lacp.end_state

    - name: Display port channel summary
      debug:
        msg: |
          Port Channel Configuration Summary:
          
          Static Port Channel (ID: {{ portchannel.group }}):
          - Type: {{ portchannel.type }}
          - Mode: {{ portchannel.mode }}
          - Member Ports: {{ interfaces | join(', ') }}
          - Min Active Ports: {{ portchannel.min_ports }}
          - Max Active Ports: {{ portchannel.max_ports }}
          
          LACP Port Channel (ID: {{ portchannel.group }}):
          - Type: {{ portchannel.type }}
          - Mode: dynamic (LACP)
          - Member Ports: {{ interfaces[0:2] | join(', ') }}
          - LACP Mode: active
          - LACP Edge: enabled
          - Min Active Ports: 2
          - Max Active Ports: 4